/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/goal/scene.gltf -r public
Author: Geri3D (https://sketchfab.com/Geri3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/football-goal-rework-26012ee6503f462c86252a35c9d35a89
Title: Football Goal Rework
*/
import { useBox } from '@react-three/cannon'

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Goal(props) {
  const { nodes, materials } = useGLTF('/goal/scene.gltf')
  
  const [ref] = useBox(() => ({
    type: 'Static',
    mass: 1,
    position: [0,-0.35,0]
  }))
  
  return (
    <group ref={ref} {...props} dispose={null} scale={3} >
      <group scale={0.01}>
        <mesh geometry={nodes.Circle_Material001_0.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} scale={[17.58, 26.75, 17.58]} />
        <mesh geometry={nodes.Cube__0.geometry} material={materials.Cube__0} position={[0, 100.93, -111.09]} rotation={[-Math.PI / 2, 0, 0]} scale={[378.62, 100, 100]} />
      </group>
    </group>
  )
}

useGLTF.preload('/goal/scene.gltf')
